p8105_hw2_xw2962
================
Xiaoyu Wu
2023-09-26

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(haven)
```

## Problem One

#### Step One: Clean Data in `pols-month.csv`

``` r
pols_df = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
# Read in dataset 
  separate(mon, into = c("year", "month_day"), sep = 4) |>
  separate(month_day, into = c("month","day"), sep = 3) |>
# Use separate() to break up the variable mon into integer variables year, month, and day
  mutate(month = recode(month, "-01" = "jan", "-02" = "feb","-03" = "mar","-04" = "apr","-05" = "may","-06" = "jun","-07" = "jul","-08" = "aug","-09" = "sep","-10" = "oct","-11" = "nov","-12" = "dec")) |> 
# Replace month number with month name 
  mutate(day=recode(day,"-15"="15")) |>
  relocate(year, month,day,prez_gop,prez_dem) |>
  pivot_longer(
   prez_gop:prez_dem,
   names_to = "president",
   names_prefix = "prez_"
   ) |>
   select(-value)|>
# Create a president variable taking values gop and dem, and remove prez_dem and prez_gop
   select(-day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Remove the day variable
pols_df
```

    ## # A tibble: 1,644 × 9
    ##    year  month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  jan        23      51     253      23      45     198 gop      
    ##  2 1947  jan        23      51     253      23      45     198 dem      
    ##  3 1947  feb        23      51     253      23      45     198 gop      
    ##  4 1947  feb        23      51     253      23      45     198 dem      
    ##  5 1947  mar        23      51     253      23      45     198 gop      
    ##  6 1947  mar        23      51     253      23      45     198 dem      
    ##  7 1947  apr        23      51     253      23      45     198 gop      
    ##  8 1947  apr        23      51     253      23      45     198 dem      
    ##  9 1947  may        23      51     253      23      45     198 gop      
    ## 10 1947  may        23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows

#### Step Two: Clean Data in `snp.csv`

``` r
snp_df = 
  read_csv("./fivethirtyeight_datasets/snp.csv") |> 
  janitor::clean_names() |> 
# Read in dataset 
  separate(date, into = c("month", "day_year"), sep = 2) |>
  separate(day_year, into = c("day","year"), sep = 2) |>
# Use separate() to break up the variable mon into integer variables year, month, and day
  mutate(month = recode(month, "1/" = "jan", "2/" = "feb","3/" = "mar","4/" = "apr","5/" = "may","6/" = "jun","7/" = "jul","8/" = "aug","9/" = "sep","10" = "oct","11" = "nov","12" = "dec")) |> 
# Replace month number with month name
  select(-day) |> 
# Remove the day variable
  arrange(year, month) |>
# Arrange according to year and month
  relocate(year, month) |>
# Organize so that year and month are the leading columns
  separate(year, into = c("null", "year"), sep = 1) |>
  select(-null)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# Remove prefix "/" in the column "year"
snp_df
```

    ## # A tibble: 787 × 3
    ##    year  month close
    ##    <chr> <chr> <dbl>
    ##  1 00    dec   1320.
    ##  2 00    nov   1315.
    ##  3 00    oct   1429.
    ##  4 01    dec   1148.
    ##  5 01    nov   1139.
    ##  6 01    oct   1060.
    ##  7 02    dec    880.
    ##  8 02    nov    936.
    ##  9 02    oct    886.
    ## 10 03    dec   1112.
    ## # ℹ 777 more rows

#### Step Three: Tidy Data in `unemployment.csv`

``` r
unemployment_df = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |>
  pivot_longer(
   jan:dec,
   names_to = "month",
   values_to = "unemployment_num"
   ) |>
  mutate(year=as.character("year"))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# mutate year from dbl to character 
unemployment_df
```

    ## # A tibble: 816 × 3
    ##    year  month unemployment_num
    ##    <chr> <chr>            <dbl>
    ##  1 year  jan                3.4
    ##  2 year  feb                3.8
    ##  3 year  mar                4  
    ##  4 year  apr                3.9
    ##  5 year  may                3.5
    ##  6 year  jun                3.6
    ##  7 year  jul                3.6
    ##  8 year  aug                3.9
    ##  9 year  sep                3.8
    ## 10 year  oct                3.7
    ## # ℹ 806 more rows

#### Join Datasets

``` r
pols_snp = 
  left_join(pols_df,snp_df,by = "year","month")
pols_snp
```

    ## # A tibble: 1,644 × 11
    ##    year  month.x gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  jan          23      51     253      23      45     198 gop      
    ##  2 1947  jan          23      51     253      23      45     198 dem      
    ##  3 1947  feb          23      51     253      23      45     198 gop      
    ##  4 1947  feb          23      51     253      23      45     198 dem      
    ##  5 1947  mar          23      51     253      23      45     198 gop      
    ##  6 1947  mar          23      51     253      23      45     198 dem      
    ##  7 1947  apr          23      51     253      23      45     198 gop      
    ##  8 1947  apr          23      51     253      23      45     198 dem      
    ##  9 1947  may          23      51     253      23      45     198 gop      
    ## 10 1947  may          23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows
    ## # ℹ 2 more variables: month.y <chr>, close <dbl>

``` r
# Join the datasets by merging snp into pols
pols_snp_unemployment=
  left_join(pols_snp,unemployment_df,by = "year","month")
pols_snp_unemployment
```

    ## # A tibble: 1,644 × 13
    ##    year  month.x gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 1947  jan          23      51     253      23      45     198 gop      
    ##  2 1947  jan          23      51     253      23      45     198 dem      
    ##  3 1947  feb          23      51     253      23      45     198 gop      
    ##  4 1947  feb          23      51     253      23      45     198 dem      
    ##  5 1947  mar          23      51     253      23      45     198 gop      
    ##  6 1947  mar          23      51     253      23      45     198 dem      
    ##  7 1947  apr          23      51     253      23      45     198 gop      
    ##  8 1947  apr          23      51     253      23      45     198 dem      
    ##  9 1947  may          23      51     253      23      45     198 gop      
    ## 10 1947  may          23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows
    ## # ℹ 4 more variables: month.y <chr>, close <dbl>, month <chr>,
    ## #   unemployment_num <dbl>

#### Short Description of Dataset

Dataset “pols_df” has 9 variables: year, month, gov_gop, sen_gop,
rep_gop, gov_dem, sen_dem, rep_dem, president. In this dataset, there
are 1644 rows. And there are 9 columns. Here we consider variables
“gov_gop”, “sen_gop”, “rep_gop”, “gov_dem”, “sen_dem”, “rep_dem” and
“president” to be important for analysis.

Dataset “snp_df” has 3 variables: year, month, close. In this dataset,
there are 787 rows. And there are 3 columns. Here we consider variables
“close” to be important for analysis.

Dataset “unemployment_df” has 3 variables: year, month,
unemployment_num. In this dataset, there are 816 rows. And there are 3
columns. Here we consider variables “unemployment_num” to be important
for analysis.

The joining dataset “pols_snp_unemployment” has 13 variables: year,
month.x, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem,
president, month.y, close, month, unemployment_num. In this dataset,
there are 1644 rows. And there are 13 columns. Here we consider
variables “gov_gop”, “sen_gop”, “rep_gop”, “gov_dem”, “sen_dem”,
“rep_dem”, “president”,“close” and “unemployment_num” to be important
for analysis.
